postgresql_databases:
  - name: awx
postgresql_users:
  - name: awx
    password: rosario
postgresql_python_library: python3-psycopg2
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'
  - option: listen_addresses
    value: '*'
postgresql_hba_entries:
  - {type: local, database: all, user: awx, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: awx, user: awx, address: '0.0.0.0/0', auth_method: "{{ postgresql_auth_method }}"}